### ISSUE TITLE
Please consider moving to WMF gerrit

### ISSUE THREAD

**Issue by osnard** [NIIF/mediawiki-extensions-Shibboleth#4]
By moving this extension to Wikimedia Foundation gerrit, it could benefit from automated tests, automated updates and translation by the TranslateWiki.net community.

You can request a WMF repo and an automatic import here: https://www.mediawiki.org/wiki/Gerrit/New_repositories/Requests

**Comment by northway** [comment]
If you want do it, I'll can help you set is up. Permission approval, etc.

**Comment by osnard** [comment]
I have created a repository request for this :https://www.mediawiki.org/w/index.php?diff=3117577&oldid=3117054&title=Gerrit/New_repositories/Requests/Entries&type=revision&diffmode=source

Please feel free to add your comments. After the the repo has been moved I will change links on https://www.mediawiki.org/wiki/Extension:Shibboleth and you could archive this repo if you want to.

**Comment by osnard** [comment]
FYI: The repo as been moved to WMF git: https://www.mediawiki.org/w/index.php?title=Gerrit/New_repositories/Requests/Entries&diff=prev&oldid=3120121
You may want to archive this repo and close this issue. Thanks.

**Comment by northway** [comment]
Thx
