### ISSUE TITLE
Wrong variable assigned to $id

### ISSUE THREAD

**Issue by daserzw** [NIIF/mediawiki-extensions-Shibboleth#6]
Hi, the fix to avoid setting  a null ID to existing user seems to be wrong: 
* it assign the (eventually) existing ID to the variable $temporaryUserId:
 `$temporaryUserId = $user->getId();`
* it verifies that the variable is not 0:
 `if ($temporaryUserId !== 0) {`
* but then it assign a new variable to $id:
 `          $id = $mId;` 

So, basically if you use `$temporaryUserId` to store the existing ID for that user, then you should assign it to `$id`.

https://github.com/NIIF/mediawiki-extensions-Shibboleth/blob/3f78cb096d0db150db2705936f1d46dc1c74e8df/Shibboleth.class.php#L37

Cheers,
Davide

**Comment by northway** [comment]
You are absolutely correct, I'm gonna clean up this mess.
